config/routes.rb
Aplanofattack::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users
  
  resources :pages do
    resources :sliders #, :name_prefix => "page_"
  end
    
  resources :sliders
  
  root :to => "home#index"
  match "about" => "home#about"
  match "privacy" => "home#privacy"
  match "terms-of-service" => "home#tos"
  match "about" => "home#about"
  match "admin" => "admin#index"
  
  match ":controller/:action/:id"
  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'

end

app/models/slider.rb
class Slider < ActiveRecord::Base
  belongs_to :pages
  validates_presence_of :name
  validates_numericality_of :height, :only_integer => true
  validates_numericality_of :width, :only_integer => true
  
  before_create :add_stock
  
  def add_stock
    self.slides = '
["<h2>Creating a Basic Slideshow</h2>\n\n<h3>Table of Contents</h3>\n\n<ol>\n  <li>Create a new slide show via the \"+ Slideshow\" tab.</li>\n  <li>Add and edit slides via the Slides tab.</li>\n  <li>Use CSS to style your slideshow</li>\n  <li>Add slideshow to your page.</li> \n</ol>","<h2>1. Creating a New Slideshow</h2>\n<p>\nNavigate to the \"+ Slideshow\" tab and click the \"new Slideshow\" link at the top.\n<br/>Here you can name your slideshow and set the width and height.\n<br/>Click save and a working sample slideshow will display.\n  </p>","<h2>2. Adding and Editing Slides</h2>\n<p>\nNavigate to the \"Edit Slides\" tab.\n<br/>New slides can be created by clicking on the \"new slide\" link.\n<br/>You can rearrange slides by dragging slides to new positions.\n<br/>Click on a green slide bar to edit its contents. \n<br/>Valid XHTML can be added to the editor.\n<br/>Delete a slide by clicking the [x] to the right end of the slide bar.\n</p>\n<p>\n<b>Note</b> that all changes are only saved when pressing <b>CTRL + S</b>\nwhile in an editor or pressing the green <b>Save Slideshow</b> button at the top right.\n  <br/>\nThis includes slide positions, new slides, deleted slides, and edited slide content.\n</p>","<h2>3. Styling Your Slideshow With CSS</h2>\n<p> \nNavigate to the CSS tab and enter valid CSS into the editor. \n<br/>You can include background images via absolute url paths.\n</p>","<h2>4. Add Slideshow to Your Page.</h2>\n<p>\nLocate the unique <b>TOKEN</b> located at the top left of the widget tab.\n<br/>Copy the token from the text input box. \n</p>\n<p>\nThe token looks like this: <b>[#slider:15]</b>\n</p>\n<p>\nMake sure all changes to your slide show is saved, then navigate to the\n\"Body\" tab. Paste the slideshow token into your body code wherever you want the slideshow to appear.\nSave your page.\n</p>"]
    '
    self.css = '
/* The main slideshow structure styling. Take care when editing these main containers.
   --------------------------------------------- */
#slideshow-wrapper {margin:auto;} /* center the slideshow */
#gallery-wrapper {border:2px solid #111; }
#gallery {
  background:#111 url("http://aplanofattack.com/system/samples/gradient.png") repeat-x bottom left;
}
#gallery div.each-slide {}

/* IMPORTANT: Always use the span tag to customize the slides especially when adding padding.
   --------------------------------------------- */
#gallery div.each-slide span.slide-container {
  display:block;
  padding:20px;
  color:#fff;
  font-size:14px;
 }
#slideshow-wrapper h1, h2, h3 {color:#fff;}
#gallery div.each-slide span.slide-container h2{margin:0; margin-bottom:10px; text-align:center;}
#gallery ol li{ margin-bottom:10px;}
/* back, next and reset links are styled here:
   --------------------------------------------- */
#buttons {position:relative; top:-50px;}
#buttons a {
display:block; padding:5px; line-height:40px; text-decoration:none;  font-weight:bold; font-size:40px; color:#ffff99;}
#buttons a:hover {color:orange;}
#buttons a#back-link {float:left;}
#buttons a#next-link {float:right; text-align:right;}
#reset {text-align:center;}

/* each slide has a unique id based on its position as follows:
   --------------------------------------------- */
#slide-1 {}
#slide-2 {}
#slide-3 {}
    '
  end
end

app/controllers/sliders_controller.rb
class SlidersController < ApplicationController
  layout false
  before_filter :require_user
  
  
  def index
    @sliders = Slider.all(
      :select => "id, name",
      :conditions => { :user_id => current_user.id, :page_id => params[:page_id] }
    )
    render :json => @sliders
  end
  
  def show
    @slider = Slider.find(
      params[:id],
      :conditions => { :user_id => current_user.id }
    )
    # quick and dirty javascript filtering =(
    render :text => 'Please omit open/close style tags in your CSS' and return unless /(<\/style)/i.match(@slider.css).nil?
    render :text => 'Please remove javascript from your CSS.' and return unless /(<script)/i.match(@slider.css).nil?
       
    @slider.slides = ActiveSupport::JSON.decode(@slider.slides)
    @slider.slides = [] unless @slider.slides.is_a?(Array)  
    @to_facebook = false;
    @standalone = true;
  end
  
  
  def edit
    @slider = Slider.find(
      params[:id],
      :conditions => { :user_id => current_user.id }
    )
    @slider.slides = ActiveSupport::JSON.decode(@slider.slides)
    @slider.slides = [] unless @slider.slides.is_a?(Array)
    
    @to_facebook = true;
    @html = render_to_string(:template => "sliders/show")
  end
   
    
  def new
    @page = Page.find(params[:page_id])
    @slider = @page.sliders.build
    @slider.height = 400
    @slider.width = 650
  end
  
  
  def create
    @page = Page.find(params[:page_id])
    @slider = @page.sliders.build(params[:slider]) 
    @slider.user_id = current_user.id
        
    if @slider.save
      render :json =>
      {
        'status'  => 'good',
        'msg'     => 'Slideshow created!',
        'created' => { 'resource' => 'sliders', 'id' => @slider.id }
      }
    elsif !@slider.valid?
      render :json => 
      {
        'status' => 'bad',
        'msg'    => "Oops! Please make sure all fields are valid!"
      }
    else
      render :json => 
      {
        'status' => 'bad',
        'msg'    => "Oops! Please try again!"
      }
    end  
  end
  

  def update
    @slider = Slider.find(
      params[:id],
      :conditions => { :user_id => current_user.id }
    ) 
    return if is_quickstart_guide(@slider) 
    
    slides = Array.new
    params[:slider_slides].each { |key, value| slides[key.to_i] = (value) } if ( !params[:slider_slides].nil? && params[:slider_slides].is_a?(Object) )
    params[:slider][:slides] = slides.compact.to_json
    
    if @slider.update_attributes(params[:slider])
      render :json => 
      {
        'status' => 'good',
        'msg'    => "Slider Updated!"
      }
    else
      render :json =>
      {
        'status' => 'bad',
        'msg'    => "Oops! Please try again!"
      }
    end  
  end
  
  
  def destroy
    return if is_sample_account
    
    @slider = Slider.find(
      params[:id], 
      :conditions => { :user_id => current_user.id }
    )
    @slider.destroy
    
    render :json =>
    {
      'status' => 'warn',
      'msg'    => "Slideshow deleted!"
    }
  end
    
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/views/sliders/edit.erb
<% form_for @slider do |f| %>
  <div class="widget-header">
    <%= f.error_messages %>
    <input name="_method" type="hidden" value="put" />
    <table class="page-head">
      <tr>
        <td style="width:130px;">
          <label>TOKEN:</label>
          <input type="text" value="[#slider:<%=@slider.id%>]" style="width:80px;" READONLY/>
        </td>
        <td style="width:150px;">
          <%= f.label :name %> <span class="star_req">*</span>
          <%= f.text_field :name,  {:style => 'width:150px', :rel => 'text_req', :style => 'width:120px' } %>
        </td>
        <td style="width:130px;">
          <%= f.label :width %> <span class="star_req">*</span>
          <%= f.text_field :width, {:style => 'width:30px', :rel => 'text_req' } %>px
        </td>
        
        <td style="width:130px;">
          <%= f.label :height %> <span class="star_req">*</span>
          <%= f.text_field :height,  {:style => 'width:30px', :rel => 'text_req' } %>px
        </td>
        
        <td class="buttons" style="width:60px;">
          <%= link_to 'delete', slider_path(@slider), :class => 'delete negative', :rel => 'sliders' %>
        </td>
                 
        <td class="buttons" style="width:120px;">
          <button type="submit" class="positive" id="save-slider">Save Slideshow</button>
        </td>
      </tr>
    </table>

    <ul id="widget-tabs">
      <li title="View sample slideshow output"><a href="#" rel="tab-widget-view" id="reload-widget-iframe">Slideshow Preview</a></li>
      <li title="Create and edit slides here"><a href="#slides" rel="tab-widget-slides">Edit Slides</a></li>
      <li title="Edit CSS here"><a href="#css" rel="tab-widget-css">Slideshow CSS</a></li>
      <li title="The Basic HTML stucture of your slideshow (READONLY)"><a href="#html" rel="tab-widget-html">(Sample Rendered Code)</a></li>    
    </ul>
  
  </div>

  <div id="tab-widget-view" class="widget-tabs">
    <div class="notes">
      View the up-to-date rendered slideshow. Edit slides via the <b>"Slides"</b> tab.
    </div>
    <div id="widget-view-container" rel="<%= @slider.id %>">&#160;</div>
  </div>

  <div id="tab-widget-slides" class="widget-tabs">
    <div class="notes">
      Create and delete slides, then drag slides to arrange their order.
      Edit slide content with the HTML editor.
      <br/>Changes are only saved when hitting <b>CTRL + S</b> while in a code editor or <b>"Save Slideshow"</b>.
    </div>
    
    <div style="float:right;width:550px;">
      <textarea id="slide-editor" style="width:100%;height:300px"></textarea>
    </div style="float:left;width:350px;">
    <div>
      <a href="#" id="new-slide" style="clear:both;">New Slide</a>
      <ul id="slides-list">
        <% @slider.slides.each_with_index do |content, index| %>
          <li title="Click to edit or drag to reorder">
            Slide <%= index %>
            <a href="#" class="remove">[x]</a>
            <textarea id="slider_slides_<%= index %>" name="slider_slides[<%= index %>]" style="display:none"><%= content %></textarea>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
    
  <div id="tab-widget-css" class="widget-tabs">
    <div class="notes">
      Add custom CSS styling to your slideshow. Study the HTML output tab to find ids, classes and tags to style. 
      <br/>Note that much of CSS3 is not allowed in facebook but will work in your preview.
      If your code is not working, the CSS is probably invalid.
    </div>  
    <%= f.text_area :css, :style => 'width:99%;height:300px;' %>
  </div>

  <div id="tab-widget-html" class="widget-tabs">
    <div class="notes">
      Rendered HTML output for your slideshow. Allows you to see how the slideshow is structured.
      Note this gets updated only once on initial slideshow load.
    </div>
    <textarea id="sample-html"><%= @html %></textarea>
  </div>  
<% end %> 
  

app/views/sliders/index.erb
<% @sliders.each do |slider| %>
  <%= slider.name %><br/>

<% end %>

app/views/sliders/new.erb
<% form_for(:slider, @slider, :url => page_sliders_path(@page) ) do |f| %>
  <%= f.error_messages %>
  <table class="page-head">
    <tr>
      <td style="width:250px;">
        <%= f.label :name %> <span class="star_req">*</span>
        <%= f.text_field :name,  {:style => 'width:150px', :rel => 'text_req', :tabindex => 1 } %>
      </td>
      <td style="width:150px;">
        <%= f.label :width %> <span class="star_req">*</span>
        <%= f.text_field :width, {:style => 'width:50px', :rel => 'text_req', :tabindex => 2  } %>px
      </td>
      
      <td style="width:150px;">
        <%= f.label :height %> <span class="star_req">*</span>
        <%= f.text_field :height,  {:style => 'width:50px', :rel => 'text_req', :tabindex => 3  } %>px
      </td>
         
      <td class="buttons" style="width:120px;">
        <button type="submit" class="positive" tabindex="4" accesskey="enter">Save Changes</button>
      </td>
    </tr>
  </table>

<% end %> 

app/views/sliders/show.erb
<% if @standalone %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Slideshow Preview</title>
  <%= javascript_include_tag "jquery-1.4.2.min"%>
  <style type="text/css">
    /* default fb style */
    body{color: #333333; font-family: "lucida grande", tahoma, verdana, arial, sans-serif;  }
    a {color:#3b5998}

  </style>
</head>
<body>
<small style="color:#555; display:block;text-align:center;">*The dotted line is the max width of the Facebook tab. Only shows in preview mode.*</small>
<div style="width: 760px; margin:auto; border:1px dashed #ccc;overflow:hidden;">
<% end %>

<style type="text/css" id="slide-widget"><%= @slider.css.gsub("\n", '') %></style>
<style type="text/css">
#slideshow-wrapper{width:<%= @slider.width %>px;}
#gallery-wrapper, #gallery, #gallery div.each-slide {width:<%= @slider.width %>px; height:<%= @slider.height %>px !important;}
#gallery-wrapper{overflow:hidden !important;}
#gallery{position: relative; left: 0px; overflow:hidden !important;}
#gallery div.each-slide {float:left !important; }
</style>

<div id="slideshow-wrapper">
  <div id="gallery-wrapper">
    <div id="gallery" onclick="return false;" title="1">
      <% @slider.slides.each_with_index do |content, index| %>
        <div id="slide-<%= index+1 %>" class="each-slide"><span class="slide-container"><%=raw Sanitize.clean(content, Sanitize::Config::CUSTOM) %></span></div>
      <% end %>
    </div>
  </div>
  <div id="buttons">
    <a href="#" id="back-link" onclick="apoa.scroll('back'); return false;">&lt;</a> 
    <a href="#" id="next-link" onclick="apoa.scroll('next'); return false;">&gt;</a> 
  </div>
  <div id="reset">
    <a href="#" id="reset-link" onclick="apoa.reset(); return false;">Reset</a>
  </div>
</div>

<% if @to_facebook %>
 <script>
  <!--
  function slideshow($Gallery, slideCount, slideWidth){
    this.scroll = function(action){
      var curSlide = Gallery.getTitle();
      if (curSlide <= 1 && action == 'back'){return false;}
      if (curSlide >= slideCount && action == 'next'){return false;}
      Animation(Gallery).by('left', ((action == 'next') ? '-' : '') + slideWidth + 'px').go(); 
      Gallery.setTitle( ((action == 'next') ? ++curSlide : --curSlide) );
      return false;
    }
    this.reset = function(){
      Animation(Gallery).to('left', '0px').go();
      Gallery.setTitle(1);
      return false;
    } 
  }
  Gallery = document.getElementById('gallery');
  slideCount = Gallery.getChildNodes().length ;
  slideWidth = <%= @slider.width %>;
  Gallery.setStyle({width: (slideCount*slideWidth) + 'px'});
  apoa = new slideshow(Gallery, slideCount, slideWidth);
  -->
 </script>
<% else %>
 <script type="text/javascript">
  /* preview mode using jquery */ 
  function slideshow($Gallery, slideCount, slideWidth){
    this.scroll = function(action){
      var curSlide = $Gallery.attr('title');
      if (curSlide <= 1 && action == 'back'){return false;}
      if (curSlide >= slideCount && action == 'next'){return false;}
      $Gallery.animate({left: ((action == 'next') ? '-=' : '+=') + slideWidth}, 'fast');
      $Gallery.attr('title', ((action == 'next') ? ++curSlide : --curSlide) );
      return false;
    }
    this.reset = function(){
      $Gallery.animate({left: 0}, 'fast');
      $Gallery.attr('title', 1);
      return false;
    } 
  }

  $(function(){
    $Gallery = $('#gallery');
    slideCount = $Gallery.children('div').length ;
    slideWidth = <%= @slider.width %>;
    $Gallery.css({width: (slideCount*slideWidth) + 'px'});
    apoa = new slideshow($Gallery, slideCount, slideWidth);
  })
 </script>
<% end %>


<% if @standalone %>
</div>
</body>
</html>
<% end %>