config/routes.rb
Aplanofattack::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users
  
  resources :pages do
    resources :sliders #, :name_prefix => "page_"
  end
    
  resources :sliders
  
  root :to => "home#index"
  match "about" => "home#about"
  match "privacy" => "home#privacy"
  match "terms-of-service" => "home#tos"
  match "about" => "home#about"
  match "admin" => "admin#index"
  
  match ":controller/:action/:id"
  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :pages
  
  after_create :add_samples
  
  def add_samples
    @page = self.pages.build
    @page.name = 'Quickstart Guide (Contains Sample Code)'
    @page.save
    
    @slider         = @page.sliders.build
    @slider.user_id = self.id
    @slider.width   = 650
    @slider.height  = 300
    @slider.name    = 'My First Slideshow'
    @slider.save
    
    sample ='
<div style="clear:both; margin:10px 50px;">
  <h4>Structure and Styling.</h4>
  <p>
    There are some basic CSS helper tags in the "page CSS" for header tags and the &lt;p&gt; tag.
    Try to use header tags, &lt;div&gt; &lt;/div&gt;, and &lt;p&gt; &lt;/p&gt; tags to markup text since Facebook likes properly coded markup.
    CSS3 does not work in Facebook. You can use inline CSS as well. 
    If in doubt, click the green <b>Facebook Preview</b> on the top right to see how your code looks in Facebook.
  </p>
  
  <h4>Images</h4>
  <p>
    Images work just fine, just make sure to use absolute paths.
    <br/>Animated gifs do not work because Facebook caches static versions of them?
    <br/>Most custom Facebook tabs are just a huge (nicely designed) splash image.
    So feel free to set that up easily.
  </p>
  
  <h4>CTRL + S To Save Code.</h4>
  <p>
    <b>CTRL + S</b> works when your cursor is in a code editor. The "Save" action saves
    all of the data associated with the resource you are working on.
    For example saving the "Page CSS" will also save the HTML, name, Fb id, etc.
    
    <br/>So feel free to navigate between tabs, but always remember to save frequently.
  </p>
  
  <p>
    Have a look at the sample code and if you need help just email <em>plusjade@gmail.com</em>
    <br/>-Thanks!
    <br/>-Jade
  </p>
</div>

<div id="happy-face">=)</div>
<div id="footer">The end</div>'

    # need the slider id.
    @page.body = "<h1 id=\"hello\">Aplanofattack Quickstart Guide.</h1>\n[#slider:#{@slider.id}]\n" + sample
    @page.css = '
/* helpers */
h1,h2,h3,h4,h5,h6{margin:0; margin-bottom:10px;}
h1{font-size:36px;}
h2{font-size:30px;}
h3{font-size:24px;}
h4{font-size:18px;}
h5{font-size:16px;}
p {line-height:1.5em; font-size:14px; margin:0; margin-bottom:10px;}

#hello{
  padding:5px;
  margin-bottom:20px;
  color:#ff7676;
  border-bottom:1px dotted #ff7676;
  text-align:center;
}
#happy-face{
  width:100px;
  text-align:center;
  margin:auto;
  margin-top:20px;
  padding:20px;
  color:#ff7676;
  font-size:72px;
  font-weight:bold;
  border:1px dotted #ff7676;
}
#footer{
  margin-top:40px;
  text-align:center;
}    
    '
    @page.save
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "home"
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  
  def new
    @user = User.new
    @user_session = UserSession.new
  end
  
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to("/admin")
    else
      @user_session = UserSession.new
      render :action => :new
    end
  end
  
  
  def show
    @user = @current_user
    render :template => 
      'users/show',
      :layout => false,
      :locals => {:user => @user} if request.xhr?
  end


  def edit
    @user = @current_user
    render :template => 
      'users/edit',
      :layout => false,
      :locals => {:user => @user} if request.xhr?
  end
  
  
  def update
    return if is_sample_account
    
    @user = @current_user
    if @user.update_attributes(params[:user])
      render :json => 
      {
        'status' => 'good',
        'msg'    => "Account Updated!"
      }
    elsif !@user.valid?
      render :json => 
      {
        'status' => 'bad',
        'msg'    => "Oops! Please make sure all fields are valid!"
      }
    else
      render :json => 
      {
        'status' => 'bad',
        'msg'    => "Oops! Please try again!"
      }
    end
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<fieldset>
  <%= form.label :email %>
  <%= form.text_field :email %>
</fieldset>

<fieldset>
  <%= form.label :password, form.object.new_record? ? nil : "Change password" %>
  <%= form.password_field :password %>
</fieldset>

<fieldset>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
</fieldset>

app/views/users/edit.erb
<h1>Edit My Account</h1>
<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path, :rel => 'facebox' %>

app/views/users/new.erb
<h1 class="cufon" style="text-align:center">Get In Good With The Beta!</h1>
<div id="signup">
  <% form_for @user, :url => account_path do |f| %>
    <%= render :partial => "form", :object => f %>
  
  <fieldset style="text-align:center">
    <button type="submit" name="submit" class="submit" style="width:260px">Register</button>
  </fieldset>
  <% end %>
</div>

<h2 class="cufon" style="margin-bottom:20px; text-align:center">Or Try Our Demo Account:</h2>
<div id="login">
<%= form_for :user_session, @user_session, :url => user_session_path do |f| %>  
  <fieldset> 
    <%= f.text_field :email, :value => 'sample@sample.com' %>
  
    <%= f.password_field :password, :value => 'sample' %>
  </fieldset>
  
  <fieldset>
    <button type="submit" name="submit" class="submit" style="width:260px">Login</button>
  </fieldset>
<% end %>

  <div id="beta">
    Aplanofattack is in <b class="colorize">beta</b>. Service is 100% free of charge.
    If service should stop, all pages will be fully exportable.
    Your feedback and help is very much appreciated.
    Thank you for your interest.
  </div>
    
</div>

app/views/users/show.erb
<p>
  <b>email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<%= link_to 'Go To Admin Panel', '/admin' %>
<br/><br/>
<%= link_to 'Edit', edit_account_path, :rel => 'facebox' %>
<br/><br/>
<%= link_to 'Logout', '/user_sessions/destroy' %>