config/routes.rb
Aplanofattack::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users
  
  resources :pages do
    resources :sliders #, :name_prefix => "page_"
  end
    
  resources :sliders
  
  root :to => "home#index"
  match "about" => "home#about"
  match "privacy" => "home#privacy"
  match "terms-of-service" => "home#tos"
  match "about" => "home#about"
  match "admin" => "admin#index"
  
  match ":controller/:action/:id"
  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'

end

app/views/pages/edit.erb
<div id="header">
  <ul id="admin-links">
    <li><%= link_to 'Account', account_path, :rel => 'facebox' %></li>
    <li><%= link_to 'Logout', '/user_sessions/destroy' %></li>
    <li><%= link_to 'My Pages', pages_path, :rel => 'facebox' %></li>
  </ul>
  
<% form_for @page do |f| %>
  <table class="page-head">
    <tr>
      <td style="width:230px;">
        <%= f.label "Page Name" %> <span class="star_req">*</span>
        <%= f.text_field :name, {:rel => 'text_req', :style => 'width:130px' } %>
      </td>
      <td style="width:250px;">
        <%= f.label 'FB Page/Profile ID' %> <span class="star_req">*</span>
        <%= f.text_field :fb_sig_page_id, {:rel => 'text_req', :style => 'width:120px' } %>
      </td>
      <td style="width:120px;color:#fff;">
        <%= f.label :publish %>
        <%= f.check_box(:publish) %> (yes)
      </td>
      <td class="buttons" style="width:140px;">
        <%= link_to 'Facebook Preview', 'http://apps.facebook.com/aplanofattack/deploy/preview/' + @page.preview_key, {:target => '_blank', :class => 'positive', :style => 'float:right; position:relative;'} %>
      </td>
      <td class="buttons" style="width:120px;">
        <button id="save-page" type="submit" class="positive" style="float:right">Save Page</button>
      </td>
    </tr>
  </table>
  <%= f.text_area :body, :style => 'display:none' %>
  <%= f.text_area :css, :style => 'display:none' %>
<% end %>

  <ul id="page-tabs">
    <li title="View the latest rendered output of your page"><a href="#" rel="tab-view" id="reload-iframe">Page Preview</a></li>
    <li title="Edit the contents of your page"><a href="#body" rel="tab-body">Page HTML</a></li>
    <li title="Edit the CSS of your main page"><a href="#css" rel="tab-css">Page CSS</a></li>
    <li title="Configure widgets to add to your page"><a href="#widget" rel="tab-widget" class="widget">+ Slideshow</a></li>
  </ul>
</div>

<div id="main" rel="<%= @page.id %>">

  <div id="tab-view" class="tab-content">
    <div style="text-align:right">
      <%= link_to '[Delete this page!]', page_path(@page), :class => 'delete', :rel => 'pages' %>
    </div>
    <div id="page-view-container" rel="<%= @page.preview_key %>">&#160;</div>
  </div>
    
  <div id="tab-body" class="tab-content">
    <div style="margin-bottom:10px; padding:3px;background:#ddf9bc;font-weight:bold; color:#000; text-align:center">
      Add a slideshow widget to your page by pasting the widget's <b>TOKEN</b> into your page body. An example TOKEN: [#slider:1]
      <br/>The token is available once you create a new slideshow via the "+ Slideshow" tab
    </div> 
    <div class="notes">
      Make sure your code is valid XHTML. Facebook is pretty strict.
      Be sure to use the "Facebook Preview" button to ensure your code works in Facebook.
      <br/>Javascript is not allowed and will be stripped out. Use the available widgets to create advanced interactions using javascript.
    </div>
    <textarea id="page_body_helper"></textarea>
  </div>
 
  <div id="tab-css" class="tab-content">
    <div class="notes">
      Add custom CSS here. Note that much of CSS3 is not allowed in facebook but will work in your preview.
      If your code is not working, the CSS is probably invalid.
    </div>
    <textarea id="page_css_helper"></textarea>
  </div>

  <div id="tab-widget" class="tab-content">
    <div id="slideshow-chooser">
      <h4>Slideshow Widgets</h4>
      <select id="sliders-list" class="widget-list">
        <option value="0">Select a Slideshow</option>
      <% @page.sliders.each do |slider| %>
        <option value="<%=edit_slider_path(slider)%>">
          <%= slider.name %> [#slider:<%=slider.id%>]
        </option>
      <% end %>
      </select>
      <%= link_to 'New Slideshow', new_page_slider_path(@page), :rel => 'facebox', :style => 'float:left' %>
    </div>
    <div id="widget-wrapper">&#160;</div>
  </div>
    
</div>

app/views/pages/index.erb
<h3>My Pages</h3>
<div style="height:110px;padding:10px; margin-bottom:10px; overflow:auto;">
  <ul id="pages-list">
  <% @user.pages.each do |page| %>
    <li>
      <%= link_to page.name, edit_page_path(page), :class => 'edit' %>
    </li>
  <% end %>
  </ul>
</div>

<% form_for(@user.pages.build) do |f| %>
  <%= f.error_messages %>
  <h3>Create New Page</h3>
  
  <fieldset class="buttons">
     <button type="submit" class="positive" tabindex="1" accesskey="enter" style="float:right">Add New Page</button>
  
    <%= f.label :name %> <span class="star_req">*</span>
     <%= f.text_field :name, :rel => 'text_req', :tabindex => 1 %>
  
  </fieldset>    

<% end %>

<style type="text/css">
  form#new_page{ width:450px; margin:auto;}
  form#new_page h3{text-align:center;}
  form#new_page input{font-size:16px; font-weight:bold; width:250px;}
  form#new_page label{font-size:16px; font-weight:bold; color:#111;}
</style>

app/views/pages/new.erb
<% form_for(@page) do |f| %>
  <%= f.error_messages %>
  
  <div class="right-half">
    Info
  </div>
  
  <div class="left-half">
    <h5>Create a New Page</h5>
    <fieldset>
      <%= f.label :name %> <span class="star_req">*</span>
      <br /><%= f.text_field :name, :rel => 'text_req' %>
    </fieldset>    

    <fieldset>
      <%= f.label 'Facebook Page or Profile ID' %> <span class="star_req">*</span>
      <br /><%= f.text_field :fb_sig_page_id, :rel => 'text_req' %>
    </fieldset> 
    
    <fieldset class="buttons">
      <button type="submit" class="positive">Add New Page</button>
    </fieldset>

  </div>
<% end %>

app/views/pages/show.erb
<h2><%= @page.name %></h2>

<%= @page.body %>
<% if !@page.css.nil? %>
  <style type="text/css"><%= @page.css %></style>
<% end %>