config/routes.rb
Aplanofattack::Application.routes.draw do

  resource :user_session
  resource :account, :controller => "users"
  resources :users
  
  resources :pages do
    resources :sliders #, :name_prefix => "page_"
  end
    
  resources :sliders
  
  root :to => "home#index"
  match "about" => "home#about"
  match "privacy" => "home#privacy"
  match "terms-of-service" => "home#tos"
  match "about" => "home#about"
  match "admin" => "admin#index"
  
  match ":controller/:action/:id"
  #map.connect ':controller/:action/:id'
  #map.connect ':controller/:action/:id.:format'

end

app/views/layouts/admin.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Admin | Facebook app creator </title>
  <%= stylesheet_link_tag "global", 'admin' %>
  <%= javascript_include_tag "jquery-1.4.2.min", 'admin/jquery-ui.min', 'facebox/facebox', 'admin/addon' %>
  <%= javascript_include_tag "codemirror/codemirror" %>
  <%= javascript_include_tag "admin/init" %>
</head>
<body>
  <div id="status-wrapper">
    <div id="status-bar">
      <div id="submitting" style="display:none">Submitting..</div>
      <div class="responding" style="display:none">&#160;</div>
    </div>
  </div>
  <span id="holder">&#160;</span>
  <ul id="footer-links">
    <li><%= link_to 'Account', account_path, :rel => 'facebox' %></li>
    <li><%= link_to 'Logout', '/user_sessions/destroy' %></li>
    <li><%= link_to 'My Pages', pages_path, :rel => 'facebox' %></li>
  </ul>
  <script type="text/javascript">
    $(function(){
      $.facebox(function(){ 
        $.get('/pages', function(view) { $.facebox(view) })
      })
    });
  </script>
<% if RAILS_ENV=='production' %>
  <script type="text/javascript">
    var clicky = { log: function(){ return; }, goal: function(){ return; }};
    var clicky_site_id = 232788;
    (function() {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = ( document.location.protocol == 'https:' ? 'https://static.getclicky.com/js' : 'http://static.getclicky.com/js' );
      ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
    })();
  </script>
  <noscript><p><img alt="Clicky" width="1" height="1" src="http://in.getclicky.com/232788ns.gif" /></p></noscript>
<% end %>
</body>
</html>

app/views/layouts/home.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Sell Custom Facebook Pages To Your Clients</title>
  <%= stylesheet_link_tag "style" %>
  <%= javascript_include_tag "jquery-1.4.2.min" %>
  <%= javascript_include_tag "cufon-yui.js", "chunkfive_400.font.js" %>
<!--[if lt IE 7]>
    <script type="text/javascript" src="js/unitpngfix.js"></script>
    <link rel="stylesheet" type="text/css" href="css/ieonly.css" />
<![endif]-->
<!--[if IE]>
    <style type="text/css">a.button_next, button.submit {border:2px solid #ccff99 !important;}</style>
<![endif]-->
</head>
<body>
  <div class="container_12">
    <div id="header">
      <ul id="main-links">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Sign Up', new_account_path %></li>
        <li><a href="/about">About</a></li>
        <li><%= link_to 'Log in', account_path %></li>
      </ul>
    </div>
    <%= yield %>
    <div id="footer">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Sign Up', new_account_path %></li>
        <li><a href="/about">About</a></li>
        <li><%= link_to 'Log in', account_path %></li>
        <li><a href="/terms-of-service">Terms of Service</a></li>
        <li><a href="/privacy">Privacy Policy</a></li>     
      </ul>
    </div>
  </div>
  <script type="text/javascript">
    $(document).ready(function(){
      Cufon.replace('h1.cufon, h2.cufon', { fontFamily: 'chunkfive' });
    });
  </script>
<% if RAILS_ENV=='production' %>
  <script type="text/javascript">
    var clicky = { log: function(){ return; }, goal: function(){ return; }};
    var clicky_site_id = 232788;
    (function() {
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = ( document.location.protocol == 'https:' ? 'https://static.getclicky.com/js' : 'http://static.getclicky.com/js' );
      ( document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0] ).appendChild( s );
    })();
  </script>
  <noscript><p><img alt="Clicky" width="1" height="1" src="http://in.getclicky.com/232788ns.gif" /></p></noscript>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-635329-11']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>
</body>
</html>